name: Python Docker CI/CD
#
# Trigger the workflow on any push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Run tests (optional, but recommended)
    - name: Run tests
      run: |
        # Add any test commands here, e.g., pytest or unittest
        echo "Tests passed!"

    # Step 4: Set up Docker build environment
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/python-app:latest

    # Step 7: (Optional) Deploy to Kubernetes or another environment (add your own commands here)
